# Generated by Django 6.0.5 on 2026-05-07 22:39

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CollectionBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_archived', models.BooleanField(db_index=True, default=False)),
                ('archived_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('archive_reason', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('todo', 'To read'), ('doing', 'Reading'), ('done', 'Read'), ('custom', 'Custom')], db_index=True, default='todo', max_length=12)),
                ('position', models.PositiveIntegerField(db_index=True, default=0)),
                ('notes', models.TextField(blank=True)),
                ('added_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'collection book',
                'verbose_name_plural': 'collection books',
                'ordering': ('collection_id', 'position', 'added_at'),
            },
        ),
        migrations.CreateModel(
            name='ReadingCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_archived', models.BooleanField(db_index=True, default=False)),
                ('archived_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('archive_reason', models.CharField(blank=True, max_length=255)),
                ('name', models.CharField(max_length=160)),
                ('slug', models.SlugField(max_length=180)),
                ('description', models.TextField(blank=True)),
                ('list_type', models.CharField(choices=[('todo', 'To read'), ('doing', 'Reading'), ('done', 'Read'), ('custom', 'Custom')], db_index=True, default='custom', max_length=12)),
                ('privacy', models.CharField(choices=[('public', 'Public'), ('private', 'Private')], db_index=True, default='public', max_length=10)),
                ('is_default', models.BooleanField(db_index=True, default=False)),
                ('item_count', models.PositiveIntegerField(default=0)),
                ('last_book_added_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'reading collection',
                'verbose_name_plural': 'reading collections',
                'ordering': ('owner_id', 'list_type', 'name'),
            },
        ),
        migrations.CreateModel(
            name='ReadingProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_archived', models.BooleanField(db_index=True, default=False)),
                ('archived_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('archive_reason', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('todo', 'To read'), ('doing', 'Reading'), ('done', 'Read'), ('custom', 'Custom')], db_index=True, default='todo', max_length=12)),
                ('current_page', models.PositiveIntegerField(default=0)),
                ('percent_complete', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('last_read_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('marked_read_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'reading progress',
                'verbose_name_plural': 'reading progress',
                'ordering': ('user_id', 'status', '-updated_at'),
            },
        ),
    ]
