# Generated by Django 6.0.5 on 2026-05-07 22:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0002_initial'),
        ('collections', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='collectionbook',
            name='added_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collection_additions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='collectionbook',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collection_items', to='books.book'),
        ),
        migrations.AddField(
            model_name='readingcollection',
            name='books',
            field=models.ManyToManyField(blank=True, related_name='collections', through='collections.CollectionBook', through_fields=('collection', 'book'), to='books.book'),
        ),
        migrations.AddField(
            model_name='readingcollection',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reading_collections', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='collectionbook',
            name='collection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='collections.readingcollection'),
        ),
        migrations.AddField(
            model_name='readingprogress',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reading_progress', to='books.book'),
        ),
        migrations.AddField(
            model_name='readingprogress',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reading_progress', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='readingcollection',
            index=models.Index(fields=['owner', 'privacy', 'list_type'], name='collection_owner_idx'),
        ),
        migrations.AddIndex(
            model_name='readingcollection',
            index=models.Index(fields=['is_archived', 'privacy'], name='collection_visible_idx'),
        ),
        migrations.AddConstraint(
            model_name='readingcollection',
            constraint=models.UniqueConstraint(fields=('owner', 'slug'), name='uniq_owner_collection_slug'),
        ),
        migrations.AddConstraint(
            model_name='readingcollection',
            constraint=models.CheckConstraint(condition=models.Q(('name', ''), _negated=True), name='collection_name_not_blank'),
        ),
        migrations.AddConstraint(
            model_name='readingcollection',
            constraint=models.CheckConstraint(condition=models.Q(('item_count__gte', 0)), name='collection_items_chk'),
        ),
        migrations.AddIndex(
            model_name='collectionbook',
            index=models.Index(fields=['collection', 'position'], name='collbook_coll_pos_idx'),
        ),
        migrations.AddIndex(
            model_name='collectionbook',
            index=models.Index(fields=['book', 'status'], name='collbook_book_status_idx'),
        ),
        migrations.AddIndex(
            model_name='collectionbook',
            index=models.Index(fields=['is_archived', 'added_at'], name='collbook_arch_added_idx'),
        ),
        migrations.AddConstraint(
            model_name='collectionbook',
            constraint=models.UniqueConstraint(fields=('collection', 'book'), name='uniq_collection_book'),
        ),
        migrations.AddConstraint(
            model_name='collectionbook',
            constraint=models.CheckConstraint(condition=models.Q(('position__gte', 0)), name='collbook_position_chk'),
        ),
        migrations.AddConstraint(
            model_name='collectionbook',
            constraint=models.CheckConstraint(condition=models.Q(('finished_at__isnull', True), ('started_at__isnull', True), ('finished_at__gte', models.F('started_at')), _connector='OR'), name='collbook_dates_chk'),
        ),
        migrations.AddIndex(
            model_name='readingprogress',
            index=models.Index(fields=['user', 'status'], name='progress_user_status_idx'),
        ),
        migrations.AddIndex(
            model_name='readingprogress',
            index=models.Index(fields=['book', 'status'], name='progress_book_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='readingprogress',
            constraint=models.UniqueConstraint(fields=('user', 'book'), name='uniq_user_book_progress'),
        ),
        migrations.AddConstraint(
            model_name='readingprogress',
            constraint=models.CheckConstraint(condition=models.Q(('percent_complete__gte', 0), ('percent_complete__lte', 100)), name='progress_percent_chk'),
        ),
        migrations.AddConstraint(
            model_name='readingprogress',
            constraint=models.CheckConstraint(condition=models.Q(('finished_at__isnull', True), ('started_at__isnull', True), ('finished_at__gte', models.F('started_at')), _connector='OR'), name='progress_dates_chk'),
        ),
    ]
