# Generated by Django 6.0.5 on 2026-05-07 22:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaskLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('task_id', models.CharField(max_length=255, unique=True)),
                ('task_type', models.CharField(choices=[('external_book_sync', 'External book sync'), ('query_enrichment', 'Query enrichment'), ('recommendation_training', 'Recommendation training'), ('recommendation_generation', 'Recommendation generation'), ('search_index_rebuild', 'Search index rebuild'), ('csv_export', 'CSV export'), ('data_repair', 'Data repair'), ('random_test_data', 'Random test data')], db_index=True, max_length=40)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('success', 'Success'), ('failure', 'Failure')], db_index=True, default='pending', max_length=20)),
                ('started_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('finished_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('error_message', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'task log',
                'verbose_name_plural': 'task logs',
                'ordering': ('-started_at', '-created_at'),
                'indexes': [models.Index(fields=['task_type', 'status'], name='tasklog_type_status_idx'), models.Index(fields=['started_at'], name='tasklog_started_idx'), models.Index(fields=['finished_at'], name='tasklog_finished_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('finished_at__isnull', True), ('finished_at__gte', models.F('started_at')), _connector='OR'), name='tasklog_finished_after_start')],
            },
        ),
    ]
