# Generated by Django 6.0.5 on 2026-05-07 22:39

import django.db.models.deletion
import django.db.models.functions.text
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0002_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('operations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchQueryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('query', models.CharField(blank=True, max_length=500)),
                ('normalized_query', models.CharField(blank=True, db_index=True, max_length=500)),
                ('filters', models.JSONField(blank=True, default=dict)),
                ('sort', models.CharField(blank=True, max_length=80)),
                ('page', models.PositiveIntegerField(default=1)),
                ('page_size', models.PositiveIntegerField(default=20)),
                ('result_count', models.PositiveIntegerField(default=0)),
                ('source', models.CharField(choices=[('fulltext', 'Full-text'), ('orm', 'ORM fallback'), ('cache', 'Cache'), ('external', 'External'), ('autocomplete', 'Autocomplete')], db_index=True, default='fulltext', max_length=20)),
                ('status', models.CharField(choices=[('success', 'Success'), ('validation_error', 'Validation error'), ('rate_limited', 'Rate limited'), ('enqueued', 'Enqueued'), ('error', 'Error')], db_index=True, default='success', max_length=24)),
                ('validation_errors', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('response_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('ip_hash', models.CharField(blank=True, db_index=True, max_length=64)),
                ('user_agent_hash', models.CharField(blank=True, max_length=64)),
                ('external_enrichment_requested', models.BooleanField(db_index=True, default=False)),
                ('cache_hit', models.BooleanField(db_index=True, default=False)),
            ],
            options={
                'verbose_name': 'search query log',
                'verbose_name_plural': 'search query logs',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='SearchThrottleBucket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scope', models.CharField(choices=[('user', 'User'), ('ip', 'IP'), ('anonymous', 'Anonymous')], db_index=True, max_length=16)),
                ('key_hash', models.CharField(db_index=True, max_length=64)),
                ('window_start', models.DateTimeField(db_index=True)),
                ('request_count', models.PositiveIntegerField(default=0)),
                ('blocked_until', models.DateTimeField(blank=True, db_index=True, null=True)),
            ],
            options={
                'verbose_name': 'search throttle bucket',
                'verbose_name_plural': 'search throttle buckets',
                'ordering': ('-window_start',),
            },
        ),
        migrations.CreateModel(
            name='SearchAutocompleteTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('term', models.CharField(max_length=255)),
                ('normalized_term', models.GeneratedField(db_index=True, db_persist=True, expression=django.db.models.functions.text.Lower('term'), output_field=models.CharField(max_length=255))),
                ('term_type', models.CharField(choices=[('book', 'Book'), ('author', 'Author'), ('genre', 'Genre'), ('isbn', 'ISBN'), ('query', 'Query')], db_index=True, max_length=16)),
                ('weight', models.PositiveIntegerField(db_index=True, default=0)),
                ('use_count', models.PositiveIntegerField(default=0)),
                ('target_object_id', models.PositiveBigIntegerField(blank=True, db_index=True, null=True)),
                ('last_seen_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('target_content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'search autocomplete term',
                'verbose_name_plural': 'search autocomplete terms',
                'ordering': ('-weight', 'term'),
            },
        ),
        migrations.CreateModel(
            name='SearchIndexStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(choices=[('books', 'Books'), ('authors', 'Authors'), ('genres', 'Genres')], max_length=24, unique=True)),
                ('status', models.CharField(choices=[('idle', 'Idle'), ('rebuilding', 'Rebuilding'), ('ready', 'Ready'), ('failed', 'Failed')], db_index=True, default='idle', max_length=20)),
                ('last_rebuilt_at', models.DateTimeField(blank=True, null=True)),
                ('document_count', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('current_task', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='search_index_status', to='operations.tasklog')),
                ('last_indexed_book', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='search_index_markers', to='books.book')),
            ],
            options={
                'verbose_name': 'search index status',
                'verbose_name_plural': 'search index statuses',
                'ordering': ('name',),
            },
        ),
    ]
