# Generated by Django 6.0.5 on 2026-05-07 22:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('search', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='searchquerylog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='search_queries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='searchthrottlebucket',
            index=models.Index(fields=['scope', 'key_hash', 'window_start'], name='throttle_scope_key_idx'),
        ),
        migrations.AddIndex(
            model_name='searchthrottlebucket',
            index=models.Index(fields=['blocked_until'], name='throttle_blocked_idx'),
        ),
        migrations.AddConstraint(
            model_name='searchthrottlebucket',
            constraint=models.UniqueConstraint(fields=('scope', 'key_hash', 'window_start'), name='uniq_throttle_bucket'),
        ),
        migrations.AddConstraint(
            model_name='searchthrottlebucket',
            constraint=models.CheckConstraint(condition=models.Q(('request_count__gte', 0)), name='throttle_count_chk'),
        ),
        migrations.AddIndex(
            model_name='searchautocompleteterm',
            index=models.Index(fields=['normalized_term', 'term_type'], name='autocomplete_norm_idx'),
        ),
        migrations.AddIndex(
            model_name='searchautocompleteterm',
            index=models.Index(fields=['term_type', 'is_active', 'weight'], name='autocomplete_type_idx'),
        ),
        migrations.AddConstraint(
            model_name='searchautocompleteterm',
            constraint=models.UniqueConstraint(fields=('term', 'term_type'), name='uniq_autocomplete_term'),
        ),
        migrations.AddConstraint(
            model_name='searchautocompleteterm',
            constraint=models.CheckConstraint(condition=models.Q(('term', ''), _negated=True), name='autocomplete_term_chk'),
        ),
        migrations.AddConstraint(
            model_name='searchautocompleteterm',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('target_content_type__isnull', True), ('target_object_id__isnull', True)), models.Q(('target_content_type__isnull', False), ('target_object_id__isnull', False)), _connector='OR'), name='autocomplete_target_chk'),
        ),
        migrations.AddIndex(
            model_name='searchindexstatus',
            index=models.Index(fields=['status'], name='searchindex_status_idx'),
        ),
        migrations.AddIndex(
            model_name='searchindexstatus',
            index=models.Index(fields=['last_rebuilt_at'], name='searchindex_rebuilt_idx'),
        ),
        migrations.AddConstraint(
            model_name='searchindexstatus',
            constraint=models.CheckConstraint(condition=models.Q(('document_count__gte', 0)), name='searchindex_count_chk'),
        ),
        migrations.AddIndex(
            model_name='searchquerylog',
            index=models.Index(fields=['normalized_query', 'status', 'created_at'], name='search_query_status_idx'),
        ),
        migrations.AddIndex(
            model_name='searchquerylog',
            index=models.Index(fields=['user', 'created_at'], name='search_user_date_idx'),
        ),
        migrations.AddIndex(
            model_name='searchquerylog',
            index=models.Index(fields=['source', 'cache_hit'], name='search_source_cache_idx'),
        ),
        migrations.AddConstraint(
            model_name='searchquerylog',
            constraint=models.CheckConstraint(condition=models.Q(('page__gte', 1)), name='search_page_chk'),
        ),
        migrations.AddConstraint(
            model_name='searchquerylog',
            constraint=models.CheckConstraint(condition=models.Q(('page_size__gte', 1)), name='search_page_size_chk'),
        ),
    ]
