# Generated by Django 6.0.5 on 2026-05-09 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='searchthrottlebucket',
            name='throttle_scope_key_idx',
        ),
        migrations.RemoveIndex(
            model_name='searchthrottlebucket',
            name='throttle_blocked_idx',
        ),
        migrations.RemoveConstraint(
            model_name='searchthrottlebucket',
            name='uniq_throttle_bucket',
        ),
        migrations.RemoveConstraint(
            model_name='searchthrottlebucket',
            name='throttle_count_chk',
        ),
        migrations.DeleteModel(
            name='SearchThrottleBucket',
        ),
    ]
