# Generated by Django 5.1.2 on 2025-06-08 16:54

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=cloudinary.models.CloudinaryField(blank=True, default='https://sbmsdpqk.manus.space/image.svg', max_length=255, null=True, verbose_name='image'),
        ),
    ]
