# Generated by Django 5.1.2 on 2025-06-09 12:28

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_profile_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, default="Hey there! I'm new to BookNest.", max_length=500),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=cloudinary.models.CloudinaryField(blank=True, default='https://liwdokry.manus.space/image.svg', max_length=255, null=True, verbose_name='image'),
        ),
    ]
