# Generated by Django 6.0.5 on 2026-05-07 22:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('actor_object_id', models.PositiveBigIntegerField(blank=True, db_index=True, null=True)),
                ('target_object_id', models.PositiveBigIntegerField(blank=True, db_index=True, null=True)),
                ('action_object_object_id', models.PositiveBigIntegerField(blank=True, db_index=True, null=True)),
                ('notification_type', models.CharField(choices=[('social', 'Social'), ('review', 'Review'), ('rating', 'Rating'), ('collection', 'Collection'), ('recommendation', 'Recommendation'), ('system', 'System')], db_index=True, max_length=24)),
                ('action', models.CharField(choices=[('followed', 'Followed'), ('rated_book', 'Rated book'), ('reviewed_book', 'Reviewed book'), ('review_upvoted', 'Review upvoted'), ('collection_shared', 'Collection shared'), ('recommendation_ready', 'Recommendation ready'), ('task_failed', 'Task failed')], db_index=True, max_length=40)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('read_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('action_object_content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='contenttypes.contenttype')),
                ('actor_content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'notification',
                'verbose_name_plural': 'notifications',
                'ordering': ('-created_at', '-id'),
            },
        ),
    ]
