# Generated by Django 6.0.5 on 2026-05-07 22:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('notifications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notification',
            name='target_content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='contenttypes.contenttype'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient', 'is_read', 'notification_type', 'created_at'], name='notif_rec_read_type_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient', 'is_deleted', 'created_at'], name='notif_rec_deleted_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['action', 'created_at'], name='notif_action_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['actor_content_type', 'actor_object_id'], name='notif_actor_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['target_content_type', 'target_object_id'], name='notif_target_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['action_object_content_type', 'action_object_object_id'], name='notif_object_idx'),
        ),
        migrations.AddConstraint(
            model_name='notification',
            constraint=models.CheckConstraint(condition=models.Q(('is_read', False), ('read_at__isnull', False), _connector='OR'), name='notif_read_time_chk'),
        ),
        migrations.AddConstraint(
            model_name='notification',
            constraint=models.CheckConstraint(condition=models.Q(('is_deleted', False), ('deleted_at__isnull', False), _connector='OR'), name='notif_delete_time_chk'),
        ),
        migrations.AddConstraint(
            model_name='notification',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('actor_content_type__isnull', True), ('actor_object_id__isnull', True)), models.Q(('actor_content_type__isnull', False), ('actor_object_id__isnull', False)), _connector='OR'), name='notif_actor_pair_chk'),
        ),
        migrations.AddConstraint(
            model_name='notification',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('target_content_type__isnull', True), ('target_object_id__isnull', True)), models.Q(('target_content_type__isnull', False), ('target_object_id__isnull', False)), _connector='OR'), name='notif_target_pair_chk'),
        ),
        migrations.AddConstraint(
            model_name='notification',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('action_object_content_type__isnull', True), ('action_object_object_id__isnull', True)), models.Q(('action_object_content_type__isnull', False), ('action_object_object_id__isnull', False)), _connector='OR'), name='notif_object_pair_chk'),
        ),
    ]
