# Generated by Django 6.0.4 on 2026-05-04 11:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('notifications', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='action_object_content_type',
            field=models.ForeignKey(blank=True, help_text='Content type for the created action object.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='action_object_notifications', to='contenttypes.contenttype', verbose_name='action object content type'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='action_object_id',
            field=models.CharField(blank=True, help_text='Primary key of the created action object.', max_length=255, null=True, verbose_name='action object ID'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='actor_content_type',
            field=models.ForeignKey(blank=True, help_text='Content type for the object that triggered the notification.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actor_notifications', to='contenttypes.contenttype', verbose_name='actor content type'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='actor_object_id',
            field=models.CharField(blank=True, help_text='Primary key of the object that triggered the notification.', max_length=255, null=True, verbose_name='actor object ID'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='data',
            field=models.JSONField(blank=True, default=dict, help_text='Additional structured notification payload.', verbose_name='data'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.ForeignKey(blank=True, help_text='Classification used for filtering notifications.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='notifications.notificationtype', verbose_name='notification type'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='read',
            field=models.BooleanField(default=False, help_text='Whether the recipient has read the notification.', verbose_name='read'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='recipient',
            field=models.ForeignKey(help_text='User who receives the notification.', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='recipient'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='target_content_type',
            field=models.ForeignKey(blank=True, help_text='Content type for the notification target object.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='target_notifications', to='contenttypes.contenttype', verbose_name='target content type'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='target_object_id',
            field=models.CharField(blank=True, help_text='Primary key of the target object.', max_length=255, null=True, verbose_name='target object ID'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp when the notification was created.', verbose_name='timestamp'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='verb',
            field=models.CharField(help_text='Short phrase describing the notification action.', max_length=255, verbose_name='verb'),
        ),
        migrations.AlterField(
            model_name='notificationtype',
            name='description',
            field=models.TextField(blank=True, help_text='Human-readable description of when this notification type is used.', verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='notificationtype',
            name='name',
            field=models.CharField(help_text='Unique machine-readable notification type name.', max_length=100, unique=True, verbose_name='name'),
        ),
    ]
