# Generated by Django 6.0.4 on 2026-05-04 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_alter_notification_action_object_content_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='id',
            field=models.BigAutoField(help_text='Primary identifier for the notification.', primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='notificationtype',
            name='id',
            field=models.BigAutoField(help_text='Primary identifier for the notification type.', primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
