# Generated by Django 6.0.5 on 2026-05-07 22:39

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='FollowRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'follow relationship',
                'verbose_name_plural': 'follow relationships',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='FeedEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_type', models.CharField(choices=[('rating_created', 'Rating created'), ('review_created', 'Review created'), ('user_followed', 'User followed'), ('collection_created', 'Collection created'), ('book_added', 'Book added')], db_index=True, max_length=32)),
                ('target_object_id', models.PositiveBigIntegerField(blank=True, db_index=True, null=True)),
                ('action_object_id', models.PositiveBigIntegerField(blank=True, db_index=True, null=True)),
                ('visibility', models.CharField(choices=[('public', 'Public'), ('followers', 'Followers'), ('private', 'Private')], db_index=True, default='public', max_length=12)),
                ('occurred_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('action_content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'feed event',
                'verbose_name_plural': 'feed events',
                'ordering': ('-occurred_at', '-id'),
            },
        ),
    ]
