# Generated by Django 6.0.5 on 2026-05-07 22:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0002_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('social', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='feedevent',
            name='actor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feed_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='feedevent',
            name='book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feed_events', to='books.book'),
        ),
        migrations.AddField(
            model_name='feedevent',
            name='target_content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='followrelationship',
            name='follower',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following_relationships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='followrelationship',
            name='following',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follower_relationships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='feedevent',
            index=models.Index(fields=['visibility', 'occurred_at'], name='feed_public_idx'),
        ),
        migrations.AddIndex(
            model_name='feedevent',
            index=models.Index(fields=['actor', 'occurred_at'], name='feed_actor_idx'),
        ),
        migrations.AddIndex(
            model_name='feedevent',
            index=models.Index(fields=['event_type', 'occurred_at'], name='feed_event_type_idx'),
        ),
        migrations.AddIndex(
            model_name='feedevent',
            index=models.Index(fields=['book', 'occurred_at'], name='feed_book_idx'),
        ),
        migrations.AddConstraint(
            model_name='feedevent',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('target_content_type__isnull', True), ('target_object_id__isnull', True)), models.Q(('target_content_type__isnull', False), ('target_object_id__isnull', False)), _connector='OR'), name='feed_target_pair_chk'),
        ),
        migrations.AddConstraint(
            model_name='feedevent',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('action_content_type__isnull', True), ('action_object_id__isnull', True)), models.Q(('action_content_type__isnull', False), ('action_object_id__isnull', False)), _connector='OR'), name='feed_action_pair_chk'),
        ),
        migrations.AddIndex(
            model_name='followrelationship',
            index=models.Index(fields=['follower'], name='follow_follower_idx'),
        ),
        migrations.AddIndex(
            model_name='followrelationship',
            index=models.Index(fields=['following'], name='follow_following_idx'),
        ),
        migrations.AddConstraint(
            model_name='followrelationship',
            constraint=models.UniqueConstraint(fields=('follower', 'following'), name='uniq_follow_pair'),
        ),
        migrations.AddConstraint(
            model_name='followrelationship',
            constraint=models.CheckConstraint(condition=models.Q(('follower_id', models.F('following_id')), _negated=True), name='no_self_follow'),
        ),
    ]
