# Generated by Django 6.0.5 on 2026-05-07 22:39

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalSyncRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sync_type', models.CharField(choices=[('full', 'Full'), ('incremental', 'Incremental'), ('query', 'Query')], db_index=True, max_length=16)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('success', 'Success'), ('failure', 'Failure')], db_index=True, default='pending', max_length=16)),
                ('query', models.CharField(blank=True, max_length=500)),
                ('started_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('books_seen', models.PositiveIntegerField(default=0)),
                ('books_created', models.PositiveIntegerField(default=0)),
                ('books_updated', models.PositiveIntegerField(default=0)),
                ('books_merged', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'external sync run',
                'verbose_name_plural': 'external sync runs',
                'ordering': ('-started_at',),
            },
        ),
        migrations.CreateModel(
            name='ExternalSyncState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sync_kind', models.CharField(db_index=True, default='catalog', max_length=32)),
                ('cursor_token', models.CharField(blank=True, max_length=500)),
                ('last_success_at', models.DateTimeField(blank=True, null=True)),
                ('last_error_at', models.DateTimeField(blank=True, null=True)),
                ('last_error_message', models.TextField(blank=True)),
                ('total_records_seen', models.PositiveIntegerField(default=0)),
                ('total_records_saved', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'external sync state',
                'verbose_name_plural': 'external sync states',
                'ordering': ('source_id',),
            },
        ),
        migrations.CreateModel(
            name='ExternalCatalogSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.CharField(choices=[('openlibrary', 'OpenLibrary'), ('google_books', 'Google Books')], max_length=32, unique=True)),
                ('display_name', models.CharField(max_length=120)),
                ('base_url', models.URLField(max_length=500)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('priority', models.PositiveSmallIntegerField(db_index=True, default=10)),
                ('rate_limit_per_minute', models.PositiveIntegerField(default=60)),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'external catalog source',
                'verbose_name_plural': 'external catalog sources',
                'ordering': ('priority', 'display_name'),
                'indexes': [models.Index(fields=['is_active', 'priority'], name='extsource_active_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('display_name', ''), _negated=True), name='extsource_name_chk'), models.CheckConstraint(condition=models.Q(('rate_limit_per_minute__gte', 1)), name='extsource_rate_chk')],
            },
        ),
        migrations.CreateModel(
            name='ExternalBookRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('external_id', models.CharField(db_index=True, max_length=255)),
                ('isbn_13', models.CharField(blank=True, db_index=True, max_length=13, validators=[django.core.validators.RegexValidator('^\\d{13}$', 'ISBN-13 must contain exactly 13 digits.')])),
                ('isbn_10', models.CharField(blank=True, db_index=True, max_length=10, validators=[django.core.validators.RegexValidator('^[0-9X]{10}$', 'ISBN-10 must contain exactly 10 digits or X.')])),
                ('title', models.CharField(blank=True, max_length=500)),
                ('subtitle', models.CharField(blank=True, max_length=500)),
                ('author_names', models.TextField(blank=True)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('normalized_payload', models.JSONField(blank=True, default=dict)),
                ('merge_status', models.CharField(choices=[('pending', 'Pending'), ('matched', 'Matched'), ('merged', 'Merged'), ('rejected', 'Rejected'), ('error', 'Error')], db_index=True, default='pending', max_length=16)),
                ('confidence', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('fetched_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('matched_book', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='external_records', to='books.book')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_records', to='integrations.externalcatalogsource')),
            ],
            options={
                'verbose_name': 'external book record',
                'verbose_name_plural': 'external book records',
                'ordering': ('-fetched_at',),
            },
        ),
        migrations.CreateModel(
            name='BookExternalIdentifier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('identifier_type', models.CharField(choices=[('work', 'Work'), ('edition', 'Edition'), ('volume', 'Volume'), ('other', 'Other')], db_index=True, default='other', max_length=16)),
                ('external_id', models.CharField(db_index=True, max_length=255)),
                ('external_url', models.URLField(blank=True, max_length=500)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_identifiers', to='books.book')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_identifiers', to='integrations.externalcatalogsource')),
            ],
            options={
                'verbose_name': 'book external identifier',
                'verbose_name_plural': 'book external identifiers',
                'ordering': ('book_id', 'source_id', 'identifier_type'),
            },
        ),
        migrations.CreateModel(
            name='ExternalEnrichmentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('query', models.CharField(blank=True, max_length=500)),
                ('isbn_13', models.CharField(blank=True, max_length=13, validators=[django.core.validators.RegexValidator('^\\d{13}$', 'ISBN-13 must contain exactly 13 digits.')])),
                ('isbn_10', models.CharField(blank=True, max_length=10, validators=[django.core.validators.RegexValidator('^[0-9X]{10}$', 'ISBN-10 must contain exactly 10 digits or X.')])),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('success', 'Success'), ('failure', 'Failure'), ('cancelled', 'Cancelled')], db_index=True, default='queued', max_length=16)),
                ('priority', models.PositiveSmallIntegerField(db_index=True, default=5)),
                ('requested_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('book', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='external_enrichment_requests', to='books.book')),
            ],
            options={
                'verbose_name': 'external enrichment request',
                'verbose_name_plural': 'external enrichment requests',
                'ordering': ('priority', 'requested_at'),
            },
        ),
    ]
