# Generated by Django 6.0.5 on 2026-05-07 22:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('operations', '0001_initial'),
        ('integrations', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='externalenrichmentrequest',
            name='requested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='external_enrichment_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='externalenrichmentrequest',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrichment_requests', to='integrations.externalcatalogsource'),
        ),
        migrations.AddField(
            model_name='externalenrichmentrequest',
            name='task_log',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='external_enrichment_request', to='operations.tasklog'),
        ),
        migrations.AddField(
            model_name='externalsyncrun',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_runs', to='integrations.externalcatalogsource'),
        ),
        migrations.AddField(
            model_name='externalsyncrun',
            name='task_log',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='external_sync_run', to='operations.tasklog'),
        ),
        migrations.AddField(
            model_name='externalsyncstate',
            name='source',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sync_state', to='integrations.externalcatalogsource'),
        ),
        migrations.AddIndex(
            model_name='externalbookrecord',
            index=models.Index(fields=['source', 'merge_status'], name='extrec_source_status_idx'),
        ),
        migrations.AddIndex(
            model_name='externalbookrecord',
            index=models.Index(fields=['isbn_13'], name='extrec_isbn13_idx'),
        ),
        migrations.AddIndex(
            model_name='externalbookrecord',
            index=models.Index(fields=['isbn_10'], name='extrec_isbn10_idx'),
        ),
        migrations.AddIndex(
            model_name='externalbookrecord',
            index=models.Index(fields=['matched_book'], name='extrec_matched_idx'),
        ),
        migrations.AddConstraint(
            model_name='externalbookrecord',
            constraint=models.UniqueConstraint(fields=('source', 'external_id'), name='uniq_ext_record'),
        ),
        migrations.AddConstraint(
            model_name='externalbookrecord',
            constraint=models.CheckConstraint(condition=models.Q(('external_id', ''), _negated=True), name='extrec_external_id_chk'),
        ),
        migrations.AddConstraint(
            model_name='externalbookrecord',
            constraint=models.CheckConstraint(condition=models.Q(('confidence__isnull', True), models.Q(('confidence__gte', 0), ('confidence__lte', 1)), _connector='OR'), name='extrec_confidence_chk'),
        ),
        migrations.AddIndex(
            model_name='bookexternalidentifier',
            index=models.Index(fields=['source', 'external_id'], name='extid_source_idx'),
        ),
        migrations.AddIndex(
            model_name='bookexternalidentifier',
            index=models.Index(fields=['book', 'source'], name='extid_book_source_idx'),
        ),
        migrations.AddConstraint(
            model_name='bookexternalidentifier',
            constraint=models.UniqueConstraint(fields=('source', 'identifier_type', 'external_id'), name='uniq_ext_identifier'),
        ),
        migrations.AddConstraint(
            model_name='bookexternalidentifier',
            constraint=models.UniqueConstraint(fields=('book', 'source', 'identifier_type'), name='uniq_book_extid_type'),
        ),
        migrations.AddConstraint(
            model_name='bookexternalidentifier',
            constraint=models.CheckConstraint(condition=models.Q(('external_id', ''), _negated=True), name='extid_not_blank'),
        ),
        migrations.AddIndex(
            model_name='externalenrichmentrequest',
            index=models.Index(fields=['status', 'priority', 'requested_at'], name='enrich_status_prio_idx'),
        ),
        migrations.AddIndex(
            model_name='externalenrichmentrequest',
            index=models.Index(fields=['book'], name='enrich_book_idx'),
        ),
        migrations.AddIndex(
            model_name='externalenrichmentrequest',
            index=models.Index(fields=['requested_by'], name='enrich_user_idx'),
        ),
        migrations.AddConstraint(
            model_name='externalenrichmentrequest',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('query', ''), _negated=True), ('book__isnull', False), models.Q(('isbn_13', ''), _negated=True), models.Q(('isbn_10', ''), _negated=True), _connector='OR'), name='enrich_has_input_chk'),
        ),
        migrations.AddConstraint(
            model_name='externalenrichmentrequest',
            constraint=models.CheckConstraint(condition=models.Q(('completed_at__isnull', True), ('started_at__isnull', True), ('completed_at__gte', models.F('started_at')), _connector='OR'), name='enrich_dates_chk'),
        ),
        migrations.AddIndex(
            model_name='externalsyncrun',
            index=models.Index(fields=['source', 'status'], name='sync_source_status_idx'),
        ),
        migrations.AddIndex(
            model_name='externalsyncrun',
            index=models.Index(fields=['sync_type', 'started_at'], name='sync_type_started_idx'),
        ),
        migrations.AddConstraint(
            model_name='externalsyncrun',
            constraint=models.CheckConstraint(condition=models.Q(('finished_at__isnull', True), ('finished_at__gte', models.F('started_at')), _connector='OR'), name='sync_finished_chk'),
        ),
        migrations.AddIndex(
            model_name='externalsyncstate',
            index=models.Index(fields=['sync_kind'], name='syncstate_kind_idx'),
        ),
    ]
