# Generated by Django 6.0.5 on 2026-05-09 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0002_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='externalcatalogsource',
            name='extsource_rate_chk',
        ),
        migrations.RemoveField(
            model_name='externalcatalogsource',
            name='rate_limit_per_minute',
        ),
    ]
