# Generated by Django 6.0.4 on 2026-05-04 11:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('follows', '0002_initial'),
        ('users', '0002_alter_profile_bio_alter_profile_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='follow',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp when the follow relationship was created.', verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='follow',
            name='followed',
            field=models.ForeignKey(help_text='Profile being followed.', on_delete=django.db.models.deletion.CASCADE, related_name='followers', to='users.profile', verbose_name='followed'),
        ),
        migrations.AlterField(
            model_name='follow',
            name='follower',
            field=models.ForeignKey(help_text='Profile that initiated the follow relationship.', on_delete=django.db.models.deletion.CASCADE, related_name='following', to='users.profile', verbose_name='follower'),
        ),
    ]
