# Generated by Django 6.0.4 on 2026-05-04 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('follows', '0003_alter_follow_created_at_alter_follow_followed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='follow',
            name='id',
            field=models.BigAutoField(help_text='Primary identifier for the follow relationship.', primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
