# Generated by Django 6.0.4 on 2026-05-04 10:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('notifications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notification',
            name='target_content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='target_notifications', to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='notification',
            name='notification_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='notifications.notificationtype'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient'], name='notificatio_recipie_be3f1a_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['read'], name='notificatio_read_df532f_idx'),
        ),
    ]
