# Generated by Django 5.1.2 on 2025-05-09 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='notification',
            new_name='notificatio_recipie_be3f1a_idx',
            old_name='notif_recipient_idx',
        ),
        migrations.RenameIndex(
            model_name='notification',
            new_name='notificatio_read_df532f_idx',
            old_name='notif_read_idx',
        ),
    ]
