# Generated by Django 6.0.4 on 2026-05-04 10:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bookrating',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bookreview',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='books.book'),
        ),
        migrations.AddField(
            model_name='bookreview',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='genre',
            index=models.Index(fields=['name'], name='genre_name_idx'),
        ),
        migrations.AddField(
            model_name='book',
            name='genres',
            field=models.ManyToManyField(related_name='books', to='books.genre'),
        ),
        migrations.AddField(
            model_name='readinglist',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reading_lists', to='users.profile'),
        ),
        migrations.AddField(
            model_name='readinglistbooks',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reading_list_books', to='books.book'),
        ),
        migrations.AddField(
            model_name='readinglistbooks',
            name='readinglist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reading_list_books', to='books.readinglist'),
        ),
        migrations.AddField(
            model_name='readinglist',
            name='books',
            field=models.ManyToManyField(through='books.ReadingListBooks', to='books.book'),
        ),
        migrations.AddField(
            model_name='reviewupvote',
            name='review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upvotes', to='books.bookreview'),
        ),
        migrations.AddField(
            model_name='reviewupvote',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_upvotes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reviewvote',
            name='review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='books.bookreview'),
        ),
        migrations.AddField(
            model_name='reviewvote',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_votes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='bookauthor',
            unique_together={('book', 'author')},
        ),
        migrations.AlterUniqueTogether(
            name='bookrating',
            unique_together={('user', 'book')},
        ),
        migrations.AddIndex(
            model_name='bookreview',
            index=models.Index(fields=['-upvotes_count'], name='review_upvotes_idx'),
        ),
        migrations.AddIndex(
            model_name='bookreview',
            index=models.Index(fields=['-created_at'], name='review_created_idx'),
        ),
        migrations.AddIndex(
            model_name='bookreview',
            index=models.Index(fields=['book', '-upvotes_count'], name='book_review_upvotes_idx'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['average_rate'], name='book_rating_idx'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['publication_date'], name='book_pub_date_idx'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['number_of_pages'], name='book_pages_idx'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['number_of_ratings'], name='book_ratings_count_idx'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['average_rate', 'publication_date'], name='book_rating_date_idx'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['title', 'average_rate'], name='book_title_rating_idx'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['last_updated'], name='book_last_updated_idx'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['source'], name='book_source_idx'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['language'], name='book_language_idx'),
        ),
        migrations.AddIndex(
            model_name='reviewupvote',
            index=models.Index(fields=['review'], name='upvote_review_idx'),
        ),
        migrations.AddIndex(
            model_name='reviewupvote',
            index=models.Index(fields=['user'], name='upvote_user_idx'),
        ),
        migrations.AddIndex(
            model_name='reviewupvote',
            index=models.Index(fields=['created_at'], name='upvote_created_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='reviewupvote',
            unique_together={('user', 'review')},
        ),
        migrations.AddIndex(
            model_name='reviewvote',
            index=models.Index(fields=['review'], name='vote_review_idx'),
        ),
        migrations.AddIndex(
            model_name='reviewvote',
            index=models.Index(fields=['user'], name='vote_user_idx'),
        ),
        migrations.AddIndex(
            model_name='reviewvote',
            index=models.Index(fields=['vote_type'], name='vote_type_idx'),
        ),
        migrations.AddIndex(
            model_name='reviewvote',
            index=models.Index(fields=['created_at'], name='vote_created_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='reviewvote',
            unique_together={('user', 'review')},
        ),
    ]
