# Generated by Django 5.1.2 on 2025-05-13 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookauthor',
            options={'ordering': ['-id']},
        ),
        migrations.AlterUniqueTogether(
            name='bookauthor',
            unique_together={('book', 'author')},
        ),
    ]
