# Generated by Django 5.1.2 on 2025-05-23 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_alter_bookauthor_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['-average_rate', 'title']},
        ),
        migrations.AddIndex(
            model_name='author',
            index=models.Index(fields=['name'], name='author_name_idx'),
        ),
        migrations.AddIndex(
            model_name='author',
            index=models.Index(fields=['date_of_birth'], name='author_birth_date_idx'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['title'], name='book_title_idx'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['description'], name='book_description_idx'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['average_rate'], name='book_rating_idx'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['publication_date'], name='book_pub_date_idx'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['number_of_pages'], name='book_pages_idx'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['number_of_ratings'], name='book_ratings_count_idx'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['average_rate', 'publication_date'], name='book_rating_date_idx'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['title', 'average_rate'], name='book_title_rating_idx'),
        ),
        migrations.AddIndex(
            model_name='bookgenre',
            index=models.Index(fields=['genre'], name='book_genre_idx'),
        ),
        migrations.AddIndex(
            model_name='bookgenre',
            index=models.Index(fields=['book', 'genre'], name='book_genre_composite_idx'),
        ),
    ]
