# Generated by Django 5.1.2 on 2025-05-23 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_alter_book_options_author_author_name_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='data_quality',
            field=models.CharField(choices=[('complete', 'Complete'), ('partial', 'Partial'), ('minimal', 'Minimal')], default='minimal', max_length=20),
        ),
        migrations.AddField(
            model_name='author',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='number_of_books',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name='bookgenre',
            unique_together={('book', 'genre')},
        ),
    ]
