# Generated by Django 5.1.2 on 2025-05-26 10:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_author_data_quality_author_last_updated_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewUpvote',
            fields=[
                ('upvote_id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'Review_Upvote',
            },
        ),
        migrations.AddField(
            model_name='bookreview',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='bookreview',
            name='upvotes_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name='bookreview',
            index=models.Index(fields=['-upvotes_count'], name='review_upvotes_idx'),
        ),
        migrations.AddIndex(
            model_name='bookreview',
            index=models.Index(fields=['-created_at'], name='review_created_idx'),
        ),
        migrations.AddIndex(
            model_name='bookreview',
            index=models.Index(fields=['book', '-upvotes_count'], name='book_review_upvotes_idx'),
        ),
        migrations.AddField(
            model_name='reviewupvote',
            name='review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upvotes', to='books.bookreview'),
        ),
        migrations.AddField(
            model_name='reviewupvote',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_upvotes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='reviewupvote',
            index=models.Index(fields=['review'], name='upvote_review_idx'),
        ),
        migrations.AddIndex(
            model_name='reviewupvote',
            index=models.Index(fields=['user'], name='upvote_user_idx'),
        ),
        migrations.AddIndex(
            model_name='reviewupvote',
            index=models.Index(fields=['created_at'], name='upvote_created_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='reviewupvote',
            unique_together={('user', 'review')},
        ),
    ]
