# Generated by Django 5.1.2 on 2025-06-04 13:38

import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.utils.timezone
from django.db import migrations, models
from django.contrib.postgres.indexes import GinIndex


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_enable_postgres_extensions'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='book',
            name='book_title_idx',
        ),
        migrations.RemoveIndex(
            model_name='book',
            name='book_description_idx',
        ),
        migrations.AddField(
            model_name='book',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='external_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='external_source',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='book',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='source',
            field=models.CharField(choices=[('database', 'Database'), ('external', 'External API'), ('user', 'User Added')], default='database', max_length=20),
        ),
        migrations.AddIndex(
            model_name='book',
            index=GinIndex(fields=['title'], name='book_title_gin_idx', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='book',
            index=GinIndex(fields=['description'], name='book_description_gin_idx', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['last_updated'], name='book_last_updated_idx'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['source'], name='book_source_idx'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['external_source'], name='book_external_source_idx'),
        ),
    ]
