# Generated by Django 5.1.2 on 2025-06-04 14:27

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_remove_book_book_title_idx_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='book',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='book_search_vector_idx'),
        ),
    ]
