# Generated by Django 5.1.2 on 2025-06-07 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0012_book_genres_delete_bookgenre'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='language',
            field=models.TextField(blank=True, help_text='Comma-separated list of languages', null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='source',
            field=models.CharField(choices=[('database', 'Database'), ('openlibrary', 'OpenLibrary'), ('googlebooks', 'Google Books'), ('user', 'User Added')], default='database', max_length=20),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['language'], name='book_language_idx'),
        ),
    ]
