# Generated by Django 5.1.2 on 2025-06-07 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0013_book_language_alter_book_source_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='author',
            name='author_birth_date_idx',
        ),
        migrations.RemoveIndex(
            model_name='book',
            name='book_external_source_idx',
        ),
        migrations.RemoveField(
            model_name='author',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='author',
            name='data_quality',
        ),
        migrations.RemoveField(
            model_name='author',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='author',
            name='last_updated',
        ),
        migrations.RemoveField(
            model_name='book',
            name='external_id',
        ),
        migrations.RemoveField(
            model_name='book',
            name='external_source',
        ),
    ]
