# Generated by Django 5.1.2 on 2025-06-07 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0014_remove_author_author_birth_date_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='external_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='external_source',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
