# Generated by Django 5.1.2 on 2025-06-07 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0015_book_external_id_book_external_source'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='external_id',
        ),
        migrations.RemoveField(
            model_name='book',
            name='external_source',
        ),
    ]
