# Generated by Django 6.0.5 on 2026-05-07 22:39

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecommendationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('version', models.CharField(db_index=True, max_length=64)),
                ('model_type', models.CharField(choices=[('svd', 'SVD'), ('nmf', 'NMF'), ('knn', 'KNN'), ('content', 'Content based'), ('hybrid', 'Hybrid'), ('popularity', 'Popularity')], db_index=True, max_length=24)),
                ('is_active', models.BooleanField(db_index=True, default=False)),
                ('rmse', models.DecimalField(blank=True, decimal_places=5, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('mae', models.DecimalField(blank=True, decimal_places=5, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('min_ratings_threshold', models.PositiveIntegerField(default=5)),
                ('generated_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('training_sample_size', models.PositiveIntegerField(default=0)),
                ('artifact_uri', models.CharField(blank=True, max_length=500)),
                ('metrics', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'recommendation model',
                'verbose_name_plural': 'recommendation models',
                'ordering': ('-is_active', '-generated_at'),
            },
        ),
        migrations.CreateModel(
            name='RecommendationRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('run_type', models.CharField(choices=[('train', 'Train'), ('generate', 'Generate'), ('refresh', 'Refresh')], db_index=True, max_length=16)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('success', 'Success'), ('failure', 'Failure')], db_index=True, default='pending', max_length=16)),
                ('parameters', models.JSONField(blank=True, default=dict)),
                ('started_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'recommendation run',
                'verbose_name_plural': 'recommendation runs',
                'ordering': ('-started_at',),
            },
        ),
        migrations.CreateModel(
            name='UserRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.CharField(choices=[('personalized', 'Personalized'), ('fallback', 'Fallback'), ('trending', 'Trending'), ('featured', 'Featured')], db_index=True, default='personalized', max_length=20)),
                ('rank', models.PositiveIntegerField(db_index=True)),
                ('score', models.DecimalField(decimal_places=6, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('reason', models.JSONField(blank=True, default=dict)),
                ('generated_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_dismissed', models.BooleanField(db_index=True, default=False)),
                ('viewed_at', models.DateTimeField(blank=True, null=True)),
                ('clicked_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'user recommendation',
                'verbose_name_plural': 'user recommendations',
                'ordering': ('user_id', 'rank'),
            },
        ),
        migrations.CreateModel(
            name='CatalogRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.CharField(choices=[('popular', 'Popular'), ('trending', 'Trending'), ('featured', 'Featured'), ('new_release', 'New release')], db_index=True, max_length=20)),
                ('rank', models.PositiveIntegerField(db_index=True)),
                ('score', models.DecimalField(decimal_places=6, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('generated_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('reason', models.JSONField(blank=True, default=dict)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catalog_recommendations', to='books.book')),
            ],
            options={
                'verbose_name': 'catalog recommendation',
                'verbose_name_plural': 'catalog recommendations',
                'ordering': ('source', 'rank'),
            },
        ),
        migrations.CreateModel(
            name='RecommendationFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('feedback_type', models.CharField(choices=[('viewed', 'Viewed'), ('clicked', 'Clicked'), ('dismissed', 'Dismissed'), ('not_interested', 'Not interested'), ('saved', 'Saved'), ('read', 'Read')], db_index=True, max_length=20)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendation_feedback', to='books.book')),
            ],
            options={
                'verbose_name': 'recommendation feedback',
                'verbose_name_plural': 'recommendation feedback',
                'ordering': ('-created_at',),
            },
        ),
    ]
