# Generated by Django 6.0.5 on 2026-05-07 22:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0002_initial'),
        ('operations', '0001_initial'),
        ('recommendations', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendationfeedback',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendation_feedback', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='recommendationmodel',
            index=models.Index(fields=['is_active'], name='recmodel_active_idx'),
        ),
        migrations.AddIndex(
            model_name='recommendationmodel',
            index=models.Index(fields=['model_type', 'generated_at'], name='recmodel_type_date_idx'),
        ),
        migrations.AddConstraint(
            model_name='recommendationmodel',
            constraint=models.UniqueConstraint(fields=('model_type', 'version'), name='uniq_recmodel_version'),
        ),
        migrations.AddConstraint(
            model_name='recommendationmodel',
            constraint=models.CheckConstraint(condition=models.Q(('min_ratings_threshold__gte', 0)), name='recmodel_minratings_chk'),
        ),
        migrations.AddField(
            model_name='recommendationrun',
            name='model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='runs', to='recommendations.recommendationmodel'),
        ),
        migrations.AddField(
            model_name='recommendationrun',
            name='requested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recommendation_runs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='recommendationrun',
            name='task_log',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recommendation_run', to='operations.tasklog'),
        ),
        migrations.AddField(
            model_name='userrecommendation',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_recommendations', to='books.book'),
        ),
        migrations.AddField(
            model_name='userrecommendation',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_recommendations', to='recommendations.recommendationmodel'),
        ),
        migrations.AddField(
            model_name='userrecommendation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='recommendationfeedback',
            name='recommendation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedback', to='recommendations.userrecommendation'),
        ),
        migrations.AddIndex(
            model_name='catalogrecommendation',
            index=models.Index(fields=['source', 'is_active', 'rank'], name='catrec_source_rank_idx'),
        ),
        migrations.AddIndex(
            model_name='catalogrecommendation',
            index=models.Index(fields=['generated_at'], name='catrec_generated_idx'),
        ),
        migrations.AddConstraint(
            model_name='catalogrecommendation',
            constraint=models.UniqueConstraint(fields=('source', 'generated_at', 'rank'), name='uniq_catrec_batch_rank'),
        ),
        migrations.AddConstraint(
            model_name='catalogrecommendation',
            constraint=models.CheckConstraint(condition=models.Q(('rank__gte', 1)), name='catrec_rank_chk'),
        ),
        migrations.AddIndex(
            model_name='recommendationrun',
            index=models.Index(fields=['run_type', 'status'], name='recrun_type_status_idx'),
        ),
        migrations.AddIndex(
            model_name='recommendationrun',
            index=models.Index(fields=['started_at'], name='recrun_started_idx'),
        ),
        migrations.AddConstraint(
            model_name='recommendationrun',
            constraint=models.CheckConstraint(condition=models.Q(('finished_at__isnull', True), ('finished_at__gte', models.F('started_at')), _connector='OR'), name='recrun_finished_chk'),
        ),
        migrations.AddIndex(
            model_name='userrecommendation',
            index=models.Index(fields=['user', 'is_active', 'rank'], name='userrec_user_rank_idx'),
        ),
        migrations.AddIndex(
            model_name='userrecommendation',
            index=models.Index(fields=['book', 'score'], name='userrec_book_score_idx'),
        ),
        migrations.AddIndex(
            model_name='userrecommendation',
            index=models.Index(fields=['generated_at'], name='userrec_generated_idx'),
        ),
        migrations.AddConstraint(
            model_name='userrecommendation',
            constraint=models.UniqueConstraint(fields=('user', 'book', 'model'), name='uniq_user_book_model_rec'),
        ),
        migrations.AddConstraint(
            model_name='userrecommendation',
            constraint=models.UniqueConstraint(fields=('user', 'model', 'rank'), name='uniq_user_model_rank'),
        ),
        migrations.AddConstraint(
            model_name='userrecommendation',
            constraint=models.CheckConstraint(condition=models.Q(('rank__gte', 1)), name='userrec_rank_chk'),
        ),
        migrations.AddConstraint(
            model_name='userrecommendation',
            constraint=models.CheckConstraint(condition=models.Q(('score__gte', 0)), name='userrec_score_chk'),
        ),
        migrations.AddIndex(
            model_name='recommendationfeedback',
            index=models.Index(fields=['user', 'feedback_type'], name='recfb_user_type_idx'),
        ),
        migrations.AddIndex(
            model_name='recommendationfeedback',
            index=models.Index(fields=['book'], name='recfb_book_idx'),
        ),
        migrations.AddConstraint(
            model_name='recommendationfeedback',
            constraint=models.UniqueConstraint(fields=('user', 'book', 'feedback_type'), name='uniq_rec_feedback'),
        ),
    ]
