# Generated by Django 6.0.5 on 2026-05-07 22:39

import cloudinary.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_archived', models.BooleanField(db_index=True, default=False)),
                ('archived_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('archive_reason', models.CharField(blank=True, max_length=255)),
                ('title', models.CharField(db_index=True, max_length=500)),
                ('subtitle', models.CharField(blank=True, max_length=500)),
                ('slug', models.SlugField(max_length=520, unique=True)),
                ('description', models.TextField(blank=True)),
                ('isbn_13', models.CharField(blank=True, max_length=13, null=True, unique=True, validators=[django.core.validators.RegexValidator('^\\d{13}$', 'ISBN-13 must contain exactly 13 digits.')])),
                ('isbn_10', models.CharField(blank=True, max_length=10, null=True, unique=True, validators=[django.core.validators.RegexValidator('^[0-9X]{10}$', 'ISBN-10 must contain exactly 10 digits or X.')])),
                ('cover', cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='book_covers')),
                ('cover_fallback_url', models.CharField(blank=True, max_length=500)),
                ('publisher', models.CharField(blank=True, db_index=True, max_length=255)),
                ('publication_date', models.DateField(blank=True, db_index=True, null=True)),
                ('publication_year', models.PositiveSmallIntegerField(blank=True, db_index=True, null=True)),
                ('page_count', models.PositiveIntegerField(blank=True, db_index=True, null=True)),
                ('language', models.CharField(blank=True, db_index=True, max_length=12)),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('openlibrary', 'OpenLibrary'), ('google_books', 'Google Books'), ('import', 'Import'), ('user_submitted', 'User submitted')], db_index=True, default='manual', max_length=32)),
                ('source_updated_at', models.DateTimeField(blank=True, null=True)),
                ('external_last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('average_rating', models.DecimalField(db_index=True, decimal_places=2, default=0, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('rating_count', models.PositiveIntegerField(db_index=True, default=0)),
                ('review_count', models.PositiveIntegerField(default=0)),
                ('collection_count', models.PositiveIntegerField(default=0)),
                ('read_count', models.PositiveIntegerField(default=0)),
                ('author_names', models.TextField(blank=True)),
                ('genre_labels', models.TextField(blank=True)),
                ('is_featured', models.BooleanField(db_index=True, default=False)),
                ('featured_rank', models.PositiveIntegerField(blank=True, db_index=True, null=True)),
                ('popularity_score', models.DecimalField(db_index=True, decimal_places=4, default=0, max_digits=12)),
                ('trending_score', models.DecimalField(db_index=True, decimal_places=4, default=0, max_digits=12)),
                ('is_adult', models.BooleanField(db_index=True, default=False)),
                ('is_public', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'verbose_name': 'book',
                'verbose_name_plural': 'books',
                'ordering': ('-trending_score', 'title'),
            },
        ),
        migrations.CreateModel(
            name='BookAuthor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('author', 'Author'), ('editor', 'Editor'), ('translator', 'Translator'), ('illustrator', 'Illustrator'), ('narrator', 'Narrator'), ('contributor', 'Contributor')], db_index=True, default='author', max_length=24)),
                ('position', models.PositiveSmallIntegerField(db_index=True, default=0)),
                ('contribution_note', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'book author',
                'verbose_name_plural': 'book authors',
                'ordering': ('book_id', 'position', 'author__name'),
            },
        ),
        migrations.CreateModel(
            name='BookGenre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_primary', models.BooleanField(db_index=True, default=False)),
                ('position', models.PositiveSmallIntegerField(db_index=True, default=0)),
            ],
            options={
                'verbose_name': 'book genre',
                'verbose_name_plural': 'book genres',
                'ordering': ('book_id', 'position', 'genre__name'),
            },
        ),
        migrations.CreateModel(
            name='BookTrendSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('period', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('all_time', 'All time')], db_index=True, max_length=20)),
                ('metric_date', models.DateField(db_index=True)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('rating_count', models.PositiveIntegerField(default=0)),
                ('review_count', models.PositiveIntegerField(default=0)),
                ('collection_add_count', models.PositiveIntegerField(default=0)),
                ('search_click_count', models.PositiveIntegerField(default=0)),
                ('score', models.DecimalField(db_index=True, decimal_places=4, default=0, max_digits=12)),
            ],
            options={
                'verbose_name': 'book trend snapshot',
                'verbose_name_plural': 'book trend snapshots',
                'ordering': ('-metric_date', '-score'),
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('normalized_name', models.CharField(db_index=True, max_length=120)),
                ('slug', models.SlugField(max_length=140, unique=True)),
                ('description', models.TextField(blank=True)),
                ('books_count', models.PositiveIntegerField(db_index=True, default=0)),
                ('is_featured', models.BooleanField(db_index=True, default=False)),
                ('carousel_rank', models.PositiveIntegerField(blank=True, db_index=True, null=True)),
            ],
            options={
                'verbose_name': 'genre',
                'verbose_name_plural': 'genres',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='RelatedBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('relation_type', models.CharField(choices=[('similar', 'Similar'), ('same_author', 'Same author'), ('same_genre', 'Same genre'), ('also_liked', 'Also liked'), ('manual', 'Manual'), ('external', 'External')], db_index=True, default='similar', max_length=24)),
                ('score', models.DecimalField(decimal_places=4, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('source', models.CharField(blank=True, max_length=64)),
            ],
            options={
                'verbose_name': 'related book',
                'verbose_name_plural': 'related books',
                'ordering': ('from_book_id', '-score'),
            },
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('normalized_name', models.CharField(db_index=True, max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('bio', models.TextField(blank=True)),
                ('photo', cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='author_photos')),
                ('photo_fallback_url', models.CharField(blank=True, max_length=500)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('death_date', models.DateField(blank=True, null=True)),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('openlibrary', 'OpenLibrary'), ('google_books', 'Google Books'), ('import', 'Import')], db_index=True, default='manual', max_length=32)),
                ('books_count', models.PositiveIntegerField(db_index=True, default=0)),
                ('like_count', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'verbose_name': 'author',
                'verbose_name_plural': 'authors',
                'ordering': ('name',),
                'indexes': [models.Index(fields=['normalized_name'], name='author_norm_name_idx'), models.Index(fields=['books_count'], name='author_books_count_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('name', ''), _negated=True), name='author_name_not_blank'), models.CheckConstraint(condition=models.Q(('death_date__isnull', True), ('birth_date__isnull', True), ('death_date__gte', models.F('birth_date')), _connector='OR'), name='author_dates_chk')],
            },
        ),
        migrations.CreateModel(
            name='AuthorLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='books.author')),
            ],
            options={
                'verbose_name': 'author like',
                'verbose_name_plural': 'author likes',
                'ordering': ('-created_at',),
            },
        ),
    ]
