# Generated by Django 6.0.5 on 2026-05-07 22:39

import apps.books.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='authorlike',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bookauthor',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_authors', to='books.author'),
        ),
        migrations.AddField(
            model_name='bookauthor',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_authors', to='books.book'),
        ),
        migrations.AddField(
            model_name='book',
            name='authors',
            field=models.ManyToManyField(blank=True, related_name='books', through='books.BookAuthor', through_fields=('book', 'author'), to='books.author'),
        ),
        migrations.AddField(
            model_name='bookgenre',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_genres', to='books.book'),
        ),
        migrations.AddField(
            model_name='booktrendsnapshot',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trend_snapshots', to='books.book'),
        ),
        migrations.AddField(
            model_name='genre',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='books.genre'),
        ),
        migrations.AddField(
            model_name='bookgenre',
            name='genre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_genres', to='books.genre'),
        ),
        migrations.AddField(
            model_name='book',
            name='genres',
            field=models.ManyToManyField(blank=True, related_name='books', through='books.BookGenre', through_fields=('book', 'genre'), to='books.genre'),
        ),
        migrations.AddField(
            model_name='relatedbook',
            name='from_book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_related_books', to='books.book'),
        ),
        migrations.AddField(
            model_name='relatedbook',
            name='to_book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_related_books', to='books.book'),
        ),
        migrations.AddField(
            model_name='book',
            name='related_books',
            field=models.ManyToManyField(blank=True, related_name='related_to', through='books.RelatedBook', through_fields=('from_book', 'to_book'), to='books.book'),
        ),
        migrations.AddIndex(
            model_name='authorlike',
            index=models.Index(fields=['user'], name='authorlike_user_idx'),
        ),
        migrations.AddIndex(
            model_name='authorlike',
            index=models.Index(fields=['author'], name='authorlike_author_idx'),
        ),
        migrations.AddConstraint(
            model_name='authorlike',
            constraint=models.UniqueConstraint(fields=('user', 'author'), name='uniq_user_author_like'),
        ),
        migrations.AddIndex(
            model_name='bookauthor',
            index=models.Index(fields=['book', 'position'], name='bookauthor_book_pos_idx'),
        ),
        migrations.AddIndex(
            model_name='bookauthor',
            index=models.Index(fields=['author', 'role'], name='bookauthor_author_idx'),
        ),
        migrations.AddConstraint(
            model_name='bookauthor',
            constraint=models.UniqueConstraint(fields=('book', 'author', 'role'), name='uniq_book_author_role'),
        ),
        migrations.AddConstraint(
            model_name='bookauthor',
            constraint=models.CheckConstraint(condition=models.Q(('position__gte', 0)), name='bookauthor_pos_chk'),
        ),
        migrations.AddIndex(
            model_name='booktrendsnapshot',
            index=models.Index(fields=['period', 'metric_date', 'score'], name='trend_period_score_idx'),
        ),
        migrations.AddIndex(
            model_name='booktrendsnapshot',
            index=models.Index(fields=['book', 'period'], name='trend_book_period_idx'),
        ),
        migrations.AddConstraint(
            model_name='booktrendsnapshot',
            constraint=models.UniqueConstraint(fields=('book', 'period', 'metric_date'), name='uniq_book_trend_day'),
        ),
        migrations.AddConstraint(
            model_name='booktrendsnapshot',
            constraint=models.CheckConstraint(condition=models.Q(('score__gte', 0)), name='trend_score_nonneg_chk'),
        ),
        migrations.AddIndex(
            model_name='genre',
            index=models.Index(fields=['parent', 'name'], name='genre_parent_name_idx'),
        ),
        migrations.AddIndex(
            model_name='genre',
            index=models.Index(fields=['is_featured', 'carousel_rank'], name='genre_featured_idx'),
        ),
        migrations.AddConstraint(
            model_name='genre',
            constraint=models.CheckConstraint(condition=models.Q(('name', ''), _negated=True), name='genre_name_not_blank'),
        ),
        migrations.AddIndex(
            model_name='bookgenre',
            index=models.Index(fields=['book', 'position'], name='bookgenre_book_pos_idx'),
        ),
        migrations.AddIndex(
            model_name='bookgenre',
            index=models.Index(fields=['genre', 'is_primary'], name='bookgenre_genre_idx'),
        ),
        migrations.AddConstraint(
            model_name='bookgenre',
            constraint=models.UniqueConstraint(fields=('book', 'genre'), name='uniq_book_genre'),
        ),
        migrations.AddConstraint(
            model_name='bookgenre',
            constraint=models.CheckConstraint(condition=models.Q(('position__gte', 0)), name='bookgenre_pos_chk'),
        ),
        migrations.AddIndex(
            model_name='relatedbook',
            index=models.Index(fields=['from_book', 'score'], name='related_from_score_idx'),
        ),
        migrations.AddIndex(
            model_name='relatedbook',
            index=models.Index(fields=['to_book'], name='related_to_idx'),
        ),
        migrations.AddConstraint(
            model_name='relatedbook',
            constraint=models.UniqueConstraint(fields=('from_book', 'to_book', 'relation_type'), name='uniq_related_book_type'),
        ),
        migrations.AddConstraint(
            model_name='relatedbook',
            constraint=models.CheckConstraint(condition=models.Q(('from_book_id', models.F('to_book_id')), _negated=True), name='no_self_related_book'),
        ),
        migrations.AddConstraint(
            model_name='relatedbook',
            constraint=models.CheckConstraint(condition=models.Q(('score__gte', 0), ('score__lte', 1)), name='related_score_chk'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=apps.books.models.MariaDBFullTextIndex(fields=['title', 'subtitle', 'author_names', 'genre_labels', 'description', 'isbn_13', 'isbn_10'], name='book_fulltext_idx'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['is_archived', 'is_public', 'title'], name='book_visible_title_idx'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['average_rating', 'rating_count'], name='book_rating_idx'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['publication_year', 'page_count'], name='book_pub_pages_idx'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['is_featured', 'featured_rank'], name='book_featured_idx'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['trending_score'], name='book_trending_idx'),
        ),
        migrations.AddConstraint(
            model_name='book',
            constraint=models.CheckConstraint(condition=models.Q(('title', ''), _negated=True), name='book_title_not_blank'),
        ),
        migrations.AddConstraint(
            model_name='book',
            constraint=models.CheckConstraint(condition=models.Q(('isbn_13__isnull', True), models.Q(('isbn_13', ''), _negated=True), _connector='OR'), name='book_isbn13_not_blank'),
        ),
        migrations.AddConstraint(
            model_name='book',
            constraint=models.CheckConstraint(condition=models.Q(('isbn_10__isnull', True), models.Q(('isbn_10', ''), _negated=True), _connector='OR'), name='book_isbn10_not_blank'),
        ),
        migrations.AddConstraint(
            model_name='book',
            constraint=models.CheckConstraint(condition=models.Q(('page_count__isnull', True), ('page_count__gte', 1), _connector='OR'), name='book_page_count_chk'),
        ),
        migrations.AddConstraint(
            model_name='book',
            constraint=models.CheckConstraint(condition=models.Q(('average_rating__gte', 0), ('average_rating__lte', 5)), name='book_avg_rating_chk'),
        ),
    ]
