# Generated by Django 6.0.4 on 2026-05-04 11:15

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_initial'),
        ('users', '0002_alter_profile_bio_alter_profile_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='author_id',
            field=models.AutoField(help_text='Primary identifier for the author.', primary_key=True, serialize=False, verbose_name='author ID'),
        ),
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(help_text='Display name of the author.', max_length=255, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='author',
            name='number_of_books',
            field=models.SmallIntegerField(default=0, help_text='Cached count of books linked to this author.', verbose_name='number of books'),
        ),
        migrations.AlterField(
            model_name='book',
            name='authors',
            field=models.ManyToManyField(help_text='Authors credited for this book.', related_name='books', through='books.BookAuthor', to='books.author', verbose_name='authors'),
        ),
        migrations.AlterField(
            model_name='book',
            name='average_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Cached average rating for the book.', max_digits=3, null=True, verbose_name='average rating'),
        ),
        migrations.AlterField(
            model_name='book',
            name='cover_img',
            field=models.URLField(blank=True, help_text='URL for the book cover image.', null=True, verbose_name='cover image'),
        ),
        migrations.AlterField(
            model_name='book',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp when the book record was created.', verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='book',
            name='description',
            field=models.TextField(blank=True, help_text='Optional book description.', null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='book',
            name='genres',
            field=models.ManyToManyField(help_text='Genres associated with this book.', related_name='books', to='books.genre', verbose_name='genres'),
        ),
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.CharField(blank=True, help_text='Optional ten-digit ISBN.', max_length=10, null=True, verbose_name='ISBN-10'),
        ),
        migrations.AlterField(
            model_name='book',
            name='isbn13',
            field=models.CharField(help_text='Thirteen-digit ISBN used as the book identifier.', max_length=13, primary_key=True, serialize=False, verbose_name='ISBN-13'),
        ),
        migrations.AlterField(
            model_name='book',
            name='language',
            field=models.CharField(blank=True, help_text='Comma-separated list of languages.', max_length=100, null=True, verbose_name='language'),
        ),
        migrations.AlterField(
            model_name='book',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp when the book record was last updated.', verbose_name='last updated'),
        ),
        migrations.AlterField(
            model_name='book',
            name='number_of_pages',
            field=models.IntegerField(blank=True, help_text='Total page count when known.', null=True, verbose_name='number of pages'),
        ),
        migrations.AlterField(
            model_name='book',
            name='number_of_ratings',
            field=models.IntegerField(default=0, help_text='Cached count of ratings for the book.', verbose_name='number of ratings'),
        ),
        migrations.AlterField(
            model_name='book',
            name='publication_date',
            field=models.DateField(blank=True, help_text='Date the book was published.', null=True, verbose_name='publication date'),
        ),
        migrations.AlterField(
            model_name='book',
            name='source',
            field=models.CharField(choices=[('database', 'Database'), ('openlibrary', 'OpenLibrary'), ('googlebooks', 'Google Books'), ('user', 'User Added')], default='database', help_text='Origin of the book metadata.', max_length=20, verbose_name='source'),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(help_text='Book title.', max_length=500, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='bookauthor',
            name='author',
            field=models.ForeignKey(db_column='author_id', help_text='Author in this authorship relationship.', on_delete=django.db.models.deletion.CASCADE, to='books.author', verbose_name='author'),
        ),
        migrations.AlterField(
            model_name='bookauthor',
            name='book',
            field=models.ForeignKey(db_column='book_id', help_text='Book in this authorship relationship.', on_delete=django.db.models.deletion.CASCADE, to='books.book', verbose_name='book'),
        ),
        migrations.AlterField(
            model_name='bookauthor',
            name='id',
            field=models.AutoField(help_text='Primary identifier for the book-author relationship.', primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='bookrating',
            name='average_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Average book rating at the time this rating was saved.', max_digits=3, null=True, verbose_name='average rating'),
        ),
        migrations.AlterField(
            model_name='bookrating',
            name='book',
            field=models.ForeignKey(help_text='Book being rated.', on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='books.book', verbose_name='book'),
        ),
        migrations.AlterField(
            model_name='bookrating',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp when the rating was created.', verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='bookrating',
            name='rate',
            field=models.DecimalField(decimal_places=2, help_text='Rating value from 0 to 5.', max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='rating'),
        ),
        migrations.AlterField(
            model_name='bookrating',
            name='rate_id',
            field=models.AutoField(help_text='Primary identifier for the rating.', primary_key=True, serialize=False, verbose_name='rating ID'),
        ),
        migrations.AlterField(
            model_name='bookrating',
            name='user',
            field=models.ForeignKey(help_text='User who submitted the rating.', on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AlterField(
            model_name='bookreview',
            name='book',
            field=models.ForeignKey(help_text='Book being reviewed.', on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='books.book', verbose_name='book'),
        ),
        migrations.AlterField(
            model_name='bookreview',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp when the review was created.', verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='bookreview',
            name='downvotes_count',
            field=models.IntegerField(default=0, help_text='Cached count of downvotes on the review.', verbose_name='downvotes count'),
        ),
        migrations.AlterField(
            model_name='bookreview',
            name='review_id',
            field=models.AutoField(help_text='Primary identifier for the review.', primary_key=True, serialize=False, verbose_name='review ID'),
        ),
        migrations.AlterField(
            model_name='bookreview',
            name='review_text',
            field=models.TextField(help_text='Body text of the review.', verbose_name='review text'),
        ),
        migrations.AlterField(
            model_name='bookreview',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp when the review was last updated.', verbose_name='updated at'),
        ),
        migrations.AlterField(
            model_name='bookreview',
            name='upvotes_count',
            field=models.IntegerField(default=0, help_text='Cached count of upvotes on the review.', verbose_name='upvotes count'),
        ),
        migrations.AlterField(
            model_name='bookreview',
            name='user',
            field=models.ForeignKey(help_text='User who wrote the review.', on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp when the genre was created.', verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='description',
            field=models.TextField(blank=True, help_text='Optional description of the genre.', null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(help_text='Unique genre name.', max_length=100, unique=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp when the genre was last updated.', verbose_name='updated at'),
        ),
        migrations.AlterField(
            model_name='readinglist',
            name='books',
            field=models.ManyToManyField(help_text='Books included in this reading list.', through='books.ReadingListBooks', to='books.book', verbose_name='books'),
        ),
        migrations.AlterField(
            model_name='readinglist',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp when the reading list was created.', verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='readinglist',
            name='list_id',
            field=models.AutoField(help_text='Primary identifier for the reading list.', primary_key=True, serialize=False, verbose_name='list ID'),
        ),
        migrations.AlterField(
            model_name='readinglist',
            name='name',
            field=models.TextField(help_text='Display name for the reading list.', verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='readinglist',
            name='privacy',
            field=models.CharField(choices=[('public', 'Public'), ('private', 'Private')], default='public', help_text='Visibility setting for the reading list.', max_length=10, verbose_name='privacy'),
        ),
        migrations.AlterField(
            model_name='readinglist',
            name='profile',
            field=models.ForeignKey(help_text='Profile that owns this reading list.', on_delete=django.db.models.deletion.CASCADE, related_name='reading_lists', to='users.profile', verbose_name='profile'),
        ),
        migrations.AlterField(
            model_name='readinglist',
            name='type',
            field=models.CharField(choices=[('todo', 'To Do'), ('doing', 'Doing'), ('done', 'Done'), ('custom', 'Custom')], help_text='Reading workflow type for the list.', max_length=10, verbose_name='type'),
        ),
        migrations.AlterField(
            model_name='readinglistbooks',
            name='book',
            field=models.ForeignKey(help_text='Book included in the reading list.', on_delete=django.db.models.deletion.CASCADE, related_name='reading_list_books', to='books.book', verbose_name='book'),
        ),
        migrations.AlterField(
            model_name='readinglistbooks',
            name='id',
            field=models.AutoField(help_text='Primary identifier for the reading-list book entry.', primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='readinglistbooks',
            name='readinglist',
            field=models.ForeignKey(help_text='Reading list containing the book.', on_delete=django.db.models.deletion.CASCADE, related_name='reading_list_books', to='books.readinglist', verbose_name='reading list'),
        ),
        migrations.AlterField(
            model_name='reviewupvote',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp when the upvote was created.', verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='reviewupvote',
            name='review',
            field=models.ForeignKey(help_text='Review receiving the upvote.', on_delete=django.db.models.deletion.CASCADE, related_name='upvotes', to='books.bookreview', verbose_name='review'),
        ),
        migrations.AlterField(
            model_name='reviewupvote',
            name='upvote_id',
            field=models.AutoField(help_text='Primary identifier for the upvote.', primary_key=True, serialize=False, verbose_name='upvote ID'),
        ),
        migrations.AlterField(
            model_name='reviewupvote',
            name='user',
            field=models.ForeignKey(help_text='User who upvoted the review.', on_delete=django.db.models.deletion.CASCADE, related_name='review_upvotes', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AlterField(
            model_name='reviewvote',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp when the vote was created.', verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='reviewvote',
            name='review',
            field=models.ForeignKey(help_text='Review receiving the vote.', on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='books.bookreview', verbose_name='review'),
        ),
        migrations.AlterField(
            model_name='reviewvote',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp when the vote was last updated.', verbose_name='updated at'),
        ),
        migrations.AlterField(
            model_name='reviewvote',
            name='user',
            field=models.ForeignKey(help_text='User who cast the vote.', on_delete=django.db.models.deletion.CASCADE, related_name='review_votes', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AlterField(
            model_name='reviewvote',
            name='vote_type',
            field=models.CharField(choices=[('upvote', 'Upvote'), ('downvote', 'Downvote')], help_text='Type of vote cast on the review.', max_length=10, verbose_name='vote type'),
        ),
    ]
