# Generated by Django 6.0.5 on 2026-05-09 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='source_updated_at',
        ),
    ]
