# Generated by Django 6.0.4 on 2026-05-04 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_alter_author_author_id_alter_author_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='id',
            field=models.BigAutoField(help_text='Primary identifier for the genre.', primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='reviewvote',
            name='id',
            field=models.BigAutoField(help_text='Primary identifier for the review vote.', primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
