# Generated by Django 6.0.4 on 2026-05-04

from django.db import migrations, models
import django.db.models.deletion
from django.utils import timezone


FULLTEXT_INDEX_NAME = 'book_search_doc_ft'


def _clean_text(value):
    if value is None:
        return ''

    return ' '.join(str(value).split())


def _join_unique(values):
    seen = set()
    cleaned_values = []

    for value in values:
        cleaned = _clean_text(value)
        key = cleaned.casefold()
        if not cleaned or key in seen:
            continue

        seen.add(key)
        cleaned_values.append(cleaned)

    return ' '.join(cleaned_values)


def _weighted_document(title, authors, genres, isbn, description):
    parts = (
        [title] * 4
        + [isbn] * 4
        + [authors] * 3
        + [genres] * 2
        + [description]
    )
    return ' '.join(part for part in parts if part)


def backfill_book_search_index(apps, schema_editor):
    Book = apps.get_model('books', 'Book')
    BookSearchIndex = apps.get_model('books', 'BookSearchIndex')

    rows = []
    now = timezone.now()
    queryset = Book.objects.prefetch_related('authors', 'genres').order_by('isbn13')

    for book in queryset.iterator(chunk_size=500):
        title = _clean_text(book.title)
        authors = _join_unique(author.name for author in book.authors.all())
        genres = _join_unique(genre.name for genre in book.genres.all())
        isbn = _join_unique([book.isbn13, book.isbn])
        description = _clean_text(book.description)

        rows.append(
            BookSearchIndex(
                book_id=book.pk,
                title=title,
                authors=authors,
                genres=genres,
                isbn=isbn,
                description=description,
                document=_weighted_document(title, authors, genres, isbn, description),
                updated_at=now,
            )
        )

        if len(rows) >= 500:
            BookSearchIndex.objects.bulk_create(rows, ignore_conflicts=True)
            rows.clear()

    if rows:
        BookSearchIndex.objects.bulk_create(rows, ignore_conflicts=True)


def create_fulltext_index(apps, schema_editor):
    if schema_editor.connection.vendor != 'mysql':
        return

    with schema_editor.connection.cursor() as cursor:
        cursor.execute(
            f'ALTER TABLE book_search_index '
            f'ADD FULLTEXT INDEX {FULLTEXT_INDEX_NAME} (document)'
        )


def drop_fulltext_index(apps, schema_editor):
    if schema_editor.connection.vendor != 'mysql':
        return

    with schema_editor.connection.cursor() as cursor:
        cursor.execute(
            f'ALTER TABLE book_search_index DROP INDEX {FULLTEXT_INDEX_NAME}'
        )


class Migration(migrations.Migration):

    atomic = False

    dependencies = [
        ('books', '0004_alter_genre_id_alter_reviewvote_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookSearchIndex',
            fields=[
                (
                    'book',
                    models.OneToOneField(
                        db_column='book_id',
                        help_text='Book represented by this search document.',
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name='search_index',
                        serialize=False,
                        to='books.book',
                        verbose_name='book',
                    ),
                ),
                (
                    'title',
                    models.TextField(
                        blank=True,
                        default='',
                        help_text='Normalized title text for ranking and exact title matches.',
                        verbose_name='title',
                    ),
                ),
                (
                    'authors',
                    models.TextField(
                        blank=True,
                        default='',
                        help_text='Flattened author names for local search.',
                        verbose_name='authors',
                    ),
                ),
                (
                    'genres',
                    models.TextField(
                        blank=True,
                        default='',
                        help_text='Flattened genre names for local search.',
                        verbose_name='genres',
                    ),
                ),
                (
                    'isbn',
                    models.CharField(
                        blank=True,
                        default='',
                        help_text='Concatenated ISBN-13 and ISBN-10 values for local search.',
                        max_length=32,
                        verbose_name='ISBN values',
                    ),
                ),
                (
                    'description',
                    models.TextField(
                        blank=True,
                        default='',
                        help_text='Book description text for local search.',
                        verbose_name='description',
                    ),
                ),
                (
                    'document',
                    models.TextField(
                        blank=True,
                        default='',
                        help_text='Weighted denormalized text indexed by MariaDB FULLTEXT.',
                        verbose_name='weighted search document',
                    ),
                ),
                (
                    'updated_at',
                    models.DateTimeField(
                        auto_now=True,
                        help_text='Timestamp when this search document was last refreshed.',
                        verbose_name='updated at',
                    ),
                ),
            ],
            options={
                'db_table': 'book_search_index',
                'indexes': [
                    models.Index(fields=['updated_at'], name='book_search_updated_idx'),
                ],
            },
        ),
        migrations.RunPython(
            backfill_book_search_index,
            reverse_code=migrations.RunPython.noop,
            atomic=False,
        ),
        migrations.RunPython(
            create_fulltext_index,
            reverse_code=drop_fulltext_index,
            atomic=False,
        ),
    ]
