# Generated by Django 6.0.5 on 2026-05-07 22:39

import apps.users.models
import cloudinary.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=150)),
                ('last_name', models.CharField(blank=True, max_length=150)),
                ('display_name', models.CharField(blank=True, db_index=True, max_length=150)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_staff', models.BooleanField(db_index=True, default=False)),
                ('date_joined', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('email_verified_at', models.DateTimeField(blank=True, null=True)),
                ('password_changed_at', models.DateTimeField(blank=True, null=True)),
                ('deactivated_at', models.DateTimeField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'ordering': ('email',),
            },
            managers=[
                ('objects', apps.users.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('handle', models.SlugField(max_length=64, unique=True)),
                ('bio', models.TextField(blank=True)),
                ('profile_type', models.CharField(choices=[('reader', 'Reader'), ('creator', 'Creator'), ('librarian', 'Librarian'), ('staff', 'Staff')], db_index=True, default='reader', max_length=20)),
                ('picture', cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='profile_pictures')),
                ('picture_fallback_url', models.CharField(blank=True, max_length=500)),
                ('location', models.CharField(blank=True, max_length=120)),
                ('website_url', models.URLField(blank=True, max_length=500)),
                ('is_complete', models.BooleanField(db_index=True, default=False)),
                ('profile_completed_at', models.DateTimeField(blank=True, null=True)),
                ('completion_percent', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('followers_count', models.PositiveIntegerField(default=0)),
                ('following_count', models.PositiveIntegerField(default=0)),
                ('reviews_count', models.PositiveIntegerField(default=0)),
                ('ratings_count', models.PositiveIntegerField(default=0)),
                ('books_read_count', models.PositiveIntegerField(default=0)),
                ('collections_count', models.PositiveIntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'profile',
                'verbose_name_plural': 'profiles',
                'ordering': ('handle',),
            },
        ),
        migrations.CreateModel(
            name='ProfileInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('weight', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_interest_links', to='books.genre')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interest_links', to='users.profile')),
            ],
            options={
                'verbose_name': 'profile interest',
                'verbose_name_plural': 'profile interests',
                'ordering': ('profile_id', 'genre_id'),
            },
        ),
        migrations.AddField(
            model_name='profile',
            name='interests',
            field=models.ManyToManyField(blank=True, related_name='interested_profiles', through='users.ProfileInterest', through_fields=('profile', 'genre'), to='books.genre'),
        ),
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email_notifications_enabled', models.BooleanField(default=True)),
                ('in_app_notifications_enabled', models.BooleanField(default=True)),
                ('notify_on_follow', models.BooleanField(default=True)),
                ('notify_on_review_vote', models.BooleanField(default=True)),
                ('profile_public', models.BooleanField(db_index=True, default=True)),
                ('show_ratings_publicly', models.BooleanField(default=True)),
                ('personalized_recommendations_enabled', models.BooleanField(db_index=True, default=True)),
                ('external_enrichment_enabled', models.BooleanField(default=True)),
                ('search_history_enabled', models.BooleanField(default=True)),
                ('mature_content_enabled', models.BooleanField(default=False)),
                ('default_collection_privacy', models.CharField(choices=[('public', 'Public'), ('private', 'Private')], default='public', max_length=10)),
                ('default_language', models.CharField(blank=True, max_length=12)),
                ('timezone', models.CharField(default='UTC', max_length=64)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'user preference',
                'verbose_name_plural': 'user preferences',
                'ordering': ('user_id',),
            },
        ),
        migrations.CreateModel(
            name='UserSocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('platform', models.CharField(choices=[('website', 'Website'), ('goodreads', 'Goodreads'), ('storygraph', 'StoryGraph'), ('x', 'X'), ('instagram', 'Instagram'), ('facebook', 'Facebook'), ('tiktok', 'TikTok'), ('linkedin', 'LinkedIn')], db_index=True, max_length=30)),
                ('url', models.URLField(max_length=500)),
                ('label', models.CharField(blank=True, max_length=80)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_links', to='users.profile')),
            ],
            options={
                'verbose_name': 'user social link',
                'verbose_name_plural': 'user social links',
                'ordering': ('profile_id', 'platform'),
            },
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['is_active', 'is_staff'], name='user_active_staff_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['date_joined'], name='user_joined_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['display_name'], name='user_display_idx'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(('email', ''), _negated=True), name='user_email_not_blank'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(('deactivated_at__isnull', True), ('is_active', False), _connector='OR'), name='user_deactivated_inactive'),
        ),
        migrations.AddIndex(
            model_name='profileinterest',
            index=models.Index(fields=['profile', 'weight'], name='interest_profile_idx'),
        ),
        migrations.AddIndex(
            model_name='profileinterest',
            index=models.Index(fields=['genre'], name='interest_genre_idx'),
        ),
        migrations.AddConstraint(
            model_name='profileinterest',
            constraint=models.UniqueConstraint(fields=('profile', 'genre'), name='uniq_profile_genre'),
        ),
        migrations.AddConstraint(
            model_name='profileinterest',
            constraint=models.CheckConstraint(condition=models.Q(('weight__gte', 1), ('weight__lte', 100)), name='interest_weight_chk'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['is_complete', 'profile_type'], name='profile_complete_idx'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['followers_count'], name='profile_followers_idx'),
        ),
        migrations.AddConstraint(
            model_name='profile',
            constraint=models.CheckConstraint(condition=models.Q(('completion_percent__gte', 0), ('completion_percent__lte', 100)), name='profile_completion_chk'),
        ),
        migrations.AddConstraint(
            model_name='profile',
            constraint=models.CheckConstraint(condition=models.Q(('is_complete', False), ('profile_completed_at__isnull', False), _connector='OR'), name='profile_complete_time_chk'),
        ),
        migrations.AddIndex(
            model_name='userpreference',
            index=models.Index(fields=['profile_public'], name='pref_profile_public_idx'),
        ),
        migrations.AddIndex(
            model_name='userpreference',
            index=models.Index(fields=['personalized_recommendations_enabled'], name='pref_recs_enabled_idx'),
        ),
        migrations.AddIndex(
            model_name='usersociallink',
            index=models.Index(fields=['profile', 'platform'], name='social_profile_idx'),
        ),
        migrations.AddConstraint(
            model_name='usersociallink',
            constraint=models.UniqueConstraint(fields=('profile', 'platform'), name='uniq_profile_platform'),
        ),
    ]
