# Generated by Django 6.0.4 on 2026-05-04 11:15

import cloudinary.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, default="Hey there! I'm new to BookNest.", help_text='Short public biography for the profile.', max_length=500, verbose_name='bio'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp when the profile was created.', verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=cloudinary.models.CloudinaryField(blank=True, default='https://liwdokry.manus.space/image.svg', help_text='Profile image URL or Cloudinary public identifier.', max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_type',
            field=models.CharField(choices=[('REGULAR', 'Regular User'), ('AUTHOR', 'Author'), ('PUBLISHER', 'Publisher')], default='REGULAR', help_text='Role the profile represents in BookNest.', max_length=20, verbose_name='profile type'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='settings',
            field=models.JSONField(default=dict, help_text='User-specific profile preferences stored as JSON.', verbose_name='settings'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp when the profile was last updated.', verbose_name='updated at'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(help_text='User account that owns this profile.', on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AlterField(
            model_name='profileinterest',
            name='interest',
            field=models.CharField(help_text='Reading interest shown on the profile.', max_length=100, verbose_name='interest'),
        ),
        migrations.AlterField(
            model_name='profileinterest',
            name='profile',
            field=models.ForeignKey(help_text='Profile this interest belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='interests', to='users.profile', verbose_name='profile'),
        ),
        migrations.AlterField(
            model_name='profilesociallink',
            name='platform',
            field=models.CharField(choices=[('TWITTER', 'Twitter'), ('FACEBOOK', 'Facebook'), ('INSTAGRAM', 'Instagram'), ('LINKEDIN', 'LinkedIn'), ('GITHUB', 'GitHub'), ('WEBSITE', 'Personal Website')], help_text='Social platform for the link.', max_length=20, verbose_name='platform'),
        ),
        migrations.AlterField(
            model_name='profilesociallink',
            name='profile',
            field=models.ForeignKey(help_text='Profile this social link belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='social_links', to='users.profile', verbose_name='profile'),
        ),
        migrations.AlterField(
            model_name='profilesociallink',
            name='url',
            field=models.URLField(help_text='Absolute URL to the profile social page.', verbose_name='URL'),
        ),
    ]
