# Generated by Django 6.0.4 on 2026-05-04 11:15

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_alter_author_author_id_alter_author_name_and_more'),
        ('recommendation', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommendationmodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp when the model record was created.', verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='recommendationmodel',
            name='is_active',
            field=models.BooleanField(default=False, help_text='Whether this model is the active recommendation model.', verbose_name='is active'),
        ),
        migrations.AlterField(
            model_name='recommendationmodel',
            name='knn_k',
            field=models.IntegerField(default=40, help_text='Number of neighbors for KNN-style models.', verbose_name='neighbor count'),
        ),
        migrations.AlterField(
            model_name='recommendationmodel',
            name='mae',
            field=models.FloatField(blank=True, help_text='Mean absolute error measured during model evaluation.', null=True, verbose_name='MAE'),
        ),
        migrations.AlterField(
            model_name='recommendationmodel',
            name='min_ratings_per_user',
            field=models.IntegerField(default=5, help_text='Minimum ratings a user needs before personalized recommendations are generated.', verbose_name='minimum ratings per user'),
        ),
        migrations.AlterField(
            model_name='recommendationmodel',
            name='model_file',
            field=models.FileField(blank=True, help_text='Serialized model artifact stored in configured media storage.', null=True, upload_to='recommendation_models/', verbose_name='model file'),
        ),
        migrations.AlterField(
            model_name='recommendationmodel',
            name='model_type',
            field=models.CharField(choices=[('svd', 'Singular Value Decomposition'), ('knn', 'K-Nearest Neighbors')], help_text='Recommendation algorithm represented by this model record.', max_length=10, verbose_name='model type'),
        ),
        migrations.AlterField(
            model_name='recommendationmodel',
            name='n_factors',
            field=models.IntegerField(default=100, help_text='Number of latent factors for SVD-style models.', verbose_name='factor count'),
        ),
        migrations.AlterField(
            model_name='recommendationmodel',
            name='rmse',
            field=models.FloatField(blank=True, help_text='Root mean squared error measured during model evaluation.', null=True, verbose_name='RMSE'),
        ),
        migrations.AlterField(
            model_name='recommendationmodel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp when the model record was last updated.', verbose_name='updated at'),
        ),
        migrations.AlterField(
            model_name='userrecommendation',
            name='book',
            field=models.ForeignKey(help_text='Book recommended to the user.', on_delete=django.db.models.deletion.CASCADE, to='books.book', verbose_name='book'),
        ),
        migrations.AlterField(
            model_name='userrecommendation',
            name='model',
            field=models.ForeignKey(help_text='Recommendation model that generated this recommendation.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='recommendation.recommendationmodel', verbose_name='model'),
        ),
        migrations.AlterField(
            model_name='userrecommendation',
            name='recommended_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Timestamp when the recommendation was generated.', verbose_name='recommended at'),
        ),
        migrations.AlterField(
            model_name='userrecommendation',
            name='score',
            field=models.FloatField(help_text='Predicted rating or recommendation score.', verbose_name='score'),
        ),
        migrations.AlterField(
            model_name='userrecommendation',
            name='user',
            field=models.ForeignKey(help_text='User receiving the recommendation.', on_delete=django.db.models.deletion.CASCADE, related_name='book_recommendation', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
    ]
