# Generated by Django 6.0.4 on 2026-05-04 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0003_alter_recommendationmodel_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommendationmodel',
            name='id',
            field=models.BigAutoField(help_text='Primary identifier for the recommendation model.', primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='userrecommendation',
            name='id',
            field=models.BigAutoField(help_text='Primary identifier for the user recommendation.', primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
